function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end
    Citizen.CreateThread(function()
        Citizen.Wait(0)
        AddTextEntry("emsnspeedo", "NP ambulance")
        AddTextEntry("fordambo", "ambulance BOX")
        AddTextEntry("emsaw139", "EMS helicopter")
        AddTextEntry("npolvette", "Police Corvet")
        AddTextEntry("deluxo6str", "deluxo6str")
        AddTextEntry("contss18", "contss18")
        AddTextEntry("npolvic", "police victory")
        AddTextEntry("npolstang", "police mustang")
        AddTextEntry("npolmm", "police BMW1200gs")
        AddTextEntry("npolcoach", "police bus")
        AddTextEntry("20x5m", "BMW X5M")
        AddTextEntry("a80","Toyota Supra")
        AddTextEntry("a90e", "Toyota Supra a90e")
        AddTextEntry("e36prb", "bmw e36")
        AddTextEntry("evo9", "mitsubishi evo9")
        AddTextEntry("g65amg", "amg g65")
        AddTextEntry("HDIron883", "HDIron883")
        AddTextEntry("laferrari17", "ferrari f17")
        AddTextEntry("lfa", "lamborghini lp670")
        AddTextEntry("m1000rr", "bmw m1000rr")
        AddTextEntry("m3e46", "bmw m3e46")
        AddTextEntry("m4", "bmw m4 m3e46")
        AddTextEntry("m5e60", "bmw m5e60")
        AddTextEntry("mansamgt21", "mercedes amgt21")
        AddTextEntry("panamera17turbo", "prosche panamera")
        AddTextEntry("pistas", "maclaren pistas")
        AddTextEntry("por930", "prosche 930")
        AddTextEntry("r1", "Yamaha r1")
        AddTextEntry("r1250", "bwm r1250")
        AddTextEntry("r35", "nissan r35")
        AddTextEntry("rcf", "lexus rcf")
        AddTextEntry("rmodmustang", "mustang gt")
        AddTextEntry("s15rb", "Nissan S15RB")
        AddTextEntry("s63c217", "mercedes c63")
        AddTextEntry("senna", "maclaren senna")
        AddTextEntry("srt8b", "jeep srt8")
        AddTextEntry("zx10", "Kawasaki ZX10R")
        end)